

import { Metadata } from "next";
import { LunchboxProduct } from "./LunchboxProduct";

export const metadata: Metadata = {
    title: "FameFit",
    description: "Generated by create next app",
    openGraph: {
        title: "Lunchbox premium",
        description:
            " Stylowy i praktyczny lunchbox do pracy, szkoły lub natrening. Trzyma temperaturę i wygląda świetnie",
        images: "/images/sklep/lunchbox1.avif",
    },
};

export default function Sklep() {
    return (
        <div className="max-w-5xl mx-auto px-4 lg:py-20 py-6">
            <LunchboxProduct />
        </div>
    );
}
