import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Header/Nav";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
    title: "FameFit",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
            <body
                className={`flex flex-col min-h-screen w-full font-light antialiased font-sans bg-white`}
            >
                <Nav />
                <main className="flex-1 xl:pt-48 lg:pt-40 pt-24 w-full overflow-x-hidden relative">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
